# Generated by Django 4.2.21 on 2025-06-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_item_topic_vote_delete_user_item_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='item',
            field=models.ManyToManyField(related_name='topics', to='portfolio.item'),
        ),
    ]
