# Generated by Django 4.2.21 on 2025-06-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_topic_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='item',
        ),
    ]
